pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include: ['master']

variables:
  solution: 'MarketManager.sln'
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)/src'

steps:
- script: |
    dotnet restore '$(solution)'
    dotnet build '$(solution)' --configuration $(buildConfiguration)
    dotnet test '$(solution)' --configuration $(buildConfiguration) --logger trx
    dotnet publish ./MyProject.Web --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  workingDirectory: $(workingDirectory)

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1