# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)/src'

steps:
- script: dotnet restore ./*.sln
  displayName: Restore
  workingDirectory: $(workingDirectory)

- script: dotnet build ./*.sln --configuration $(buildConfiguration)
  displayName: Build
  workingDirectory: $(workingDirectory)

- script: dotnet test ./Tests.sln --configuration $(buildConfiguration) --logger trx
  displayName: Test
  workingDirectory: $(workingDirectory)

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./MyProject.Web --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish
  workingDirectory: $(workingDirectory)
  
- task: PublishBuildArtifacts@1
