# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)/src'

steps:
- task: NuGetToolInstaller@0
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- script: dotnet build '$(solution)' --configuration $(buildConfiguration)
  displayName: Build
  workingDirectory: $(workingDirectory)

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./MyProject.Web --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish
  workingDirectory: $(workingDirectory)
  
- task: PublishBuildArtifacts@1
